package agent_test

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/Xh12321/ctftools/internal/agent"
	"github.com/Xh12321/ctftools/internal/eventhub"
	"github.com/Xh12321/ctftools/internal/platform"
	"github.com/Xh12321/ctftools/internal/sandbox"
	"github.com/Xh12321/ctftools/internal/storage"
	"github.com/Xh12321/ctftools/internal/workspace"
)

func newTestService(t *testing.T, opts agent.FakeRunnerOptions) *agent.Service {
	t.Helper()
	store, err := storage.Open(filepath.Join(t.TempDir(), "t.db"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = store.Close() })
	hub := eventhub.New()
	t.Cleanup(hub.Close)

	wsDir := t.TempDir()
	wsMgr, err := workspace.New(workspace.Options{BaseDir: wsDir})
	if err != nil {
		t.Fatal(err)
	}

	sbMgr := sandbox.NewMockManager()

	var svc *agent.Service
	if opts.StepDelay <= 0 {
		opts.StepDelay = 5 * time.Millisecond
	}
	opts.Workspace = wsMgr
	baseOnFinding := opts.OnFinding
	opts.OnFinding = func(taskID string, f platform.FlagFinding) {
		if svc != nil {
			svc.RegisterFinding(taskID, f)
		}
		if baseOnFinding != nil {
			baseOnFinding(taskID, f)
		}
	}
	runner := agent.NewFakeRunner(opts)
	svc = agent.NewService(store, hub, runner, wsMgr, sbMgr)
	t.Cleanup(svc.Shutdown)
	return svc
}

func TestFakeAgentLifecycleAndFlagReview(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{
		FlagValue: "flag{lifecycle-ok}",
		StepDelay: 5 * time.Millisecond,
	})
	ctx := context.Background()

	task, err := svc.CreateTask(ctx, platform.CreateTask{
		Title:      "Web baby",
		Category:   platform.CategoryWeb,
		Prompt:     "find the flag",
		FlagFormat: "flag{...}",
	})
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusQueued {
		t.Fatalf("status=%s", task.Status)
	}

	// Verify workspace directory created on disk
	wsPath := svc.Workspace().WorkspacePath(task.ID)
	if fi, err := os.Stat(wsPath); err != nil || !fi.IsDir() {
		t.Fatalf("expected workspace dir %s to exist: %v", wsPath, err)
	}

	// Subscribe before start to catch live events.
	ch, cancel := svc.Hub().Subscribe(task.ID, 0, 64)
	defer cancel()

	task, err = svc.Start(ctx, task.ID)
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusRunning {
		t.Fatalf("after start status=%s", task.Status)
	}
	if task.ContainerID == "" {
		t.Fatal("expected container id")
	}

	// Wait for flag candidate event.
	deadline := time.After(3 * time.Second)
	var flagID, flagValue string
	seenTool := false
	for flagID == "" {
		select {
		case <-deadline:
			t.Fatal("timeout waiting for flag candidate")
		case ev := <-ch:
			switch ev.Type {
			case platform.EventToolStarted, platform.EventToolCompleted:
				seenTool = true
			case platform.EventFlagCandidate:
				events, _ := svc.ListEvents(ctx, task.ID, 0, 1000)
				for _, e := range events {
					if e.Type == platform.EventFlagCandidate {
						findings := svc.ListFindings(task.ID)
						if len(findings) == 0 {
							t.Fatal("flag event but no finding registered")
						}
						flagID = findings[0].ID
						flagValue = findings[0].Value
					}
				}
			}
		}
	}
	if !seenTool {
		events, _ := svc.ListEvents(ctx, task.ID, 0, 1000)
		for _, e := range events {
			if e.Type == platform.EventToolStarted {
				seenTool = true
			}
		}
	}
	if !seenTool {
		t.Fatal("expected tool events")
	}
	if flagValue != "flag{lifecycle-ok}" {
		t.Fatalf("flag=%s", flagValue)
	}

	// Verify artifact generated by fake runner in workspace
	files, err := svc.ListFiles(ctx, task.ID)
	if err != nil {
		t.Fatalf("ListFiles: %v", err)
	}
	foundSolve := false
	for _, f := range files {
		if f.Path == "scripts/solve.py" {
			foundSolve = true
		}
	}
	if !foundSolve {
		t.Fatalf("expected scripts/solve.py generated in workspace: %+v", files)
	}

	// Catch-up via after should not duplicate when combined with live.
	maxSeq, _ := svc.Store().MaxEventSequence(ctx, task.ID)
	events, err := svc.ListEvents(ctx, task.ID, maxSeq, 100)
	if err != nil {
		t.Fatal(err)
	}
	if len(events) != 0 {
		t.Fatalf("expected no events after max, got %d", len(events))
	}
	all, err := svc.ListEvents(ctx, task.ID, 0, 1000)
	if err != nil {
		t.Fatal(err)
	}
	seen := map[int64]bool{}
	for _, e := range all {
		if seen[e.Sequence] {
			t.Fatalf("duplicate sequence %d", e.Sequence)
		}
		seen[e.Sequence] = true
	}

	// Accept flag → pause
	task, err = svc.ReviewFlag(ctx, task.ID, platform.FlagFeedback{
		FlagID: flagID,
		Action: platform.FlagAccept,
		Note:   "looks good",
	})
	if err != nil {
		t.Fatal(err)
	}
	time.Sleep(30 * time.Millisecond)
	task, _ = svc.GetTask(ctx, task.ID)
	if task.Status != platform.StatusPaused && task.Status != platform.StatusSettled {
		if task.Status == platform.StatusRunning {
			t.Fatalf("expected pause after accept, status=%s", task.Status)
		}
	}

	findings := svc.ListFindings(task.ID)
	if len(findings) == 0 || !findings[0].Verified {
		t.Fatalf("findings=%+v", findings)
	}

	// Close sandbox
	if task.Status == platform.StatusRunning {
		task, _ = svc.Pause(ctx, task.ID)
	}
	cur, _ := svc.GetTask(ctx, task.ID)
	if cur.Status == platform.StatusRunning {
		_, _ = svc.Abort(ctx, task.ID)
	}
	cur, _ = svc.GetTask(ctx, task.ID)
	if cur.Status.CanCloseSandbox() {
		cur, err = svc.CloseSandbox(ctx, cur.ID)
		if err != nil {
			t.Fatal(err)
		}
		if cur.ContainerID != "" {
			t.Fatalf("container should be cleared, got %q", cur.ContainerID)
		}
	}
}

func TestPwnSandboxDegradationWarning(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{StepDelay: 10 * time.Millisecond})
	ctx := context.Background()

	task, err := svc.CreateTask(ctx, platform.CreateTask{
		Title:    "Pwn chal",
		Category: platform.CategoryPwn,
	})
	if err != nil {
		t.Fatal(err)
	}

	if _, err := svc.Start(ctx, task.ID); err != nil {
		t.Fatal(err)
	}

	events, err := svc.ListEvents(ctx, task.ID, 0, 100)
	if err != nil {
		t.Fatal(err)
	}
	foundDegraded := false
	for _, e := range events {
		if e.Type == platform.EventSandboxDegraded {
			foundDegraded = true
		}
	}
	if !foundDegraded {
		t.Fatal("expected sandbox.degraded warning event for pwn category")
	}
}

func TestAttachmentUploadAndLocking(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{StepDelay: 100 * time.Millisecond})
	ctx := context.Background()

	task, err := svc.CreateTask(ctx, platform.CreateTask{Title: "attach-test", Category: platform.CategoryWeb})
	if err != nil {
		t.Fatal(err)
	}

	// Upload while queued should succeed
	content := []byte("pcap dump content")
	info, err := svc.SaveAttachment(ctx, task.ID, "capture.pcap", bytes.NewReader(content), int64(len(content)))
	if err != nil {
		t.Fatalf("SaveAttachment: %v", err)
	}
	if info.Path != "attachments/capture.pcap" {
		t.Fatalf("unexpected info path: %s", info.Path)
	}

	// Start task
	if _, err := svc.Start(ctx, task.ID); err != nil {
		t.Fatal(err)
	}

	// Upload while running should be locked
	_, err = svc.SaveAttachment(ctx, task.ID, "locked.bin", bytes.NewReader(content), int64(len(content)))
	if !errors.Is(err, agent.ErrAttachmentsLocked) {
		t.Fatalf("expected ErrAttachmentsLocked while running, got: %v", err)
	}
}

func TestWriteupAndZipExport(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{StepDelay: 10 * time.Millisecond})
	ctx := context.Background()

	task, err := svc.CreateTask(ctx, platform.CreateTask{Title: "wu-test", Category: platform.CategoryCrypto})
	if err != nil {
		t.Fatal(err)
	}

	// Check default writeup
	wu, err := svc.GetWriteup(ctx, task.ID)
	if err != nil || !wu.Exists {
		t.Fatalf("expected initial writeup: %+v (err: %v)", wu, err)
	}

	// Update writeup
	customWU := "# Solved by crypto math"
	if err := svc.SaveWriteup(ctx, task.ID, customWU); err != nil {
		t.Fatalf("SaveWriteup: %v", err)
	}
	wu, err = svc.GetWriteup(ctx, task.ID)
	if err != nil || wu.Content != customWU {
		t.Fatalf("writeup content mismatch: %+v", wu)
	}

	// Export zip
	var buf bytes.Buffer
	if err := svc.ExportZip(ctx, task.ID, &buf); err != nil {
		t.Fatalf("ExportZip: %v", err)
	}
	if buf.Len() == 0 {
		t.Fatal("empty zip export")
	}
}

func TestPauseResumeAbort(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{StepDelay: 200 * time.Millisecond})
	ctx := context.Background()
	task, err := svc.CreateTask(ctx, platform.CreateTask{Title: "x", Category: platform.CategoryPwn})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := svc.Start(ctx, task.ID); err != nil {
		t.Fatal(err)
	}
	time.Sleep(20 * time.Millisecond)
	task, err = svc.Pause(ctx, task.ID)
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusPaused {
		t.Fatalf("status=%s", task.Status)
	}
	task, err = svc.Resume(ctx, task.ID)
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusRunning {
		t.Fatalf("status=%s", task.Status)
	}
	task, err = svc.Abort(ctx, task.ID)
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusCancelled {
		t.Fatalf("status=%s", task.Status)
	}
}

func TestRetryFromFailed(t *testing.T) {
	svc := newTestService(t, agent.FakeRunnerOptions{
		StepDelay: 5 * time.Millisecond,
		FailAfter: 1,
	})
	ctx := context.Background()
	task, _ := svc.CreateTask(ctx, platform.CreateTask{Title: "f", Category: platform.CategoryReverse})
	if _, err := svc.Start(ctx, task.ID); err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(2 * time.Second)
	for time.Now().Before(deadline) {
		cur, _ := svc.GetTask(ctx, task.ID)
		if cur.Status == platform.StatusFailed {
			break
		}
		time.Sleep(10 * time.Millisecond)
	}
	cur, _ := svc.GetTask(ctx, task.ID)
	if cur.Status != platform.StatusFailed {
		t.Fatalf("expected failed, got %s", cur.Status)
	}

	task, err := svc.Retry(ctx, task.ID)
	if err != nil {
		t.Fatal(err)
	}
	if task.Status != platform.StatusRunning && task.Status != platform.StatusProvisioning {
		if task.Status != platform.StatusFailed {
			t.Logf("retry status=%s", task.Status)
		}
	}
}
